name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a report.
        Please keep reports focused to a single issue and provide all the requested details.
  - type: textarea
    id: elpaca-version
    attributes:
      label: Elpaca Version
      description: Output of the elpaca-version command (not elpaca-installer-version)
      placeholder: Please include the output of the elpaca-version command (M-x elpaca-version)
    validations:
      required: true
  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using Emacs on?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what you expected to happen and what actually happened. Provide a reproduction case with using the elpaca-test macro when possible. If the issue concerns a single package, include the output of M-x elpaca-info for that package. Otherwise, include relevant log entries via M-x elpaca-log.
